name: Auto Register Garena

on:
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run register script
        run: |
          echo "Simulate auto register here"
